version: '3'

networks:
  network:
    driver: bridge
services:
  app:
    build: .
    image: space_flight
    container_name: node_api_space_flight
    volumes:
      - ./logs/:/app/logs/
    depends_on:
      - db
    ports:
      - '3000:3000'
    networks:
      - network
    environment:
      - PORT=3000
      - DB_HOST=mysql_space_flight
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=root
      - DB_DLCT=mysql
      - DB_NAME=space_flight
      - NODE_ENV=production
      - LOG_DIR=app/logs
  db:
    image: mysql:8.0.27
    container_name: mysql_space_flight
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3308:3306
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Sao_Paulo
    networks:
      - network