version: '3'

networks:
  network:
    driver: bridge
services:
  app:
    build: .
    image: space_flight
    depends_on:
      - db
    ports:
      - '3000:3000'
    networks:
      - network
  db:
    image: mysql:8.0.27
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3308:3306
    expose:
      - 3306
    environment:
      - MYSQL_DATABASE=space_flight
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Sao_Paulo
    networks:
      - network